name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: |
        npm ci
        npm run build --if-present
        npm test
    - uses: cloudflare/wrangler-action@1.0.0
      with:
        apiKey: ${{ secrets.CF_API_KEY }}
        email: ${{ secrets.CF_EMAIL }}
  
